### ISSUE TITLE
Support Java 8 LocalDate type

### ISSUE THREAD

**Issue by garaud** [dakrone/cheshire#104]
Hi,

Is it possible to support the new Java 8 date API : `LocalDate` and `LocalDateTime` ?
https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html

I'm a Clojure beginner but perhaps I could help.
Thanks you,
Damien

**Comment by gfredericks** [comment]
do you mean support it for reading or for writing?

For writing json, you should be able to do this yourself by extending the protocol. Is the change you're requesting just about making that support built-in so users don't have to extend the protocol manually?

**Comment by garaud** [comment]
Thank you for your answer.
It's about serialization. You're right, I'll try to extend the protocol. A built-in support could be relevant if more than one user need this support.

**Comment by garaud** [comment]
And it's quite simple by the way:
```clojure
(add-encoder java.time.LocalDate
             (fn [c jsonGenerator]
               (.writeString jsonGenerator (.toString c))))
```
I've just to put this in the right place in my Luminus Web app!
