### ISSUE TITLE
parse-string accepts top-level strings

### ISSUE THREAD

**Issue by hantuzun** [dakrone/cheshire#110]
Below is the current behavior of Cheshire:

```clj
(require '[cheshire.core :refer :all])
; nil

(parse-string "\"{0}\"")
; "{0}"
```

I'd expect Cheshire to throw an exception instead. The fact that `parse-string` function could return strings is not something I'd have expected. We get around this inconsistency by validating the output of the function at the moment.

**Comment by gfredericks** [comment]
Is there some part of [the standard](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) that I'm not seeing that says that top-level strings are not allowed?

**Comment by dakrone** [comment]
Gary Fredericks writes:

> Is there some part of [1]the standard that I'm not seeing that says
> that top-level strings are not allowed?

Yes, I was under the impression that top-level strings are allowed in
JSON, which is why this isn't an exception

--
;; Lee

**Comment by hantuzun** [comment]
Hi,

Thanks for the replies. Reading the standard, indeed for the first time, it's clear that a top-level string is a valid JSON value:

> #### **5 JSON Values**
> A JSON value can be an object, array, number, string, `true`, `false`, or `null`.

Feel free to close the issue. Apologies for the confusion. Would it be informative to add such examples to the README?

**Comment by dakrone** [comment]
Pushed a commit adding this to the readme

**Comment by hantuzun** [comment]
Thanks a lot @dakrone, for this and all of your OS contributions.
