### ISSUE TITLE
generate-stream holds onto the head of lazy-seqs

### ISSUE THREAD

**Issue by senior** [dakrone/cheshire#112]
We noticed a memory issue in [PuppetDB](https://github.com/puppetlabs/puppetdb/). We found that large streamed JSON responses weren't GC'd until the full response was returned. We were able to track it down to the [generate function](https://github.com/dakrone/cheshire/blob/master/src/cheshire/generate.clj#L122) in Cheshire. It looks like the problem is the usage of `condp` is holding onto the head of the `lazy-seq`. `condp` expands to 

```
(let [pred__74060 instance? expr__74061 obj]
  (if (pred__74060 clojure.lang.IPersistentMap expr__74061)
    (generate-map jg obj date-format ex key-fn)
    (if (pred__74060 clojure.lang.IPersistentVector expr__74061)
      (generate-array jg obj date-format ex key-fn)
      (if (pred__74060 clojure.lang.IPersistentSet expr__74061)
        (generate-array jg obj date-format ex key-fn)
        (if (pred__74060 clojure.lang.IPersistentList expr__74061)
          (generate-array jg obj date-format ex key-fn)
          (if (pred__74060 clojure.lang.ISeq expr__74061)
            (generate-array jg obj date-format ex key-fn)
            (if (pred__74060 clojure.lang.Associative expr__74061)
              (generate-map jg obj date-format ex key-fn)
              (throw
                (java.lang.IllegalArgumentException.
                  (str "No matching clause: " expr__74061))))))))))
```

In the above code, `obj` is a large `lazy-seq`. The let is holding onto the head. Switching to a more verbose `cond` should fix it.

**Comment by dakrone** [comment]
Released 5.7.1 with this fix, thanks again!
