### ISSUE TITLE
Generating symbols

### ISSUE THREAD

**Issue by delenius** [dakrone/cheshire#138]
When parsing, is there a way to turn strings in symbols for certain fields? For example, from

```json
{ "node-type": "type1", "value": "foo" }
```

I want to generate

```
{ :node-type 'type1, :value "foo" }
```

Or is the string-vs-symbol distinction irrevocably lost when you encode into JSON?
It looks like the decoder-function that you can pass to `decode` only deals with handling arrays.

**Comment by dakrone** [comment]
Hi @delenius , there isn't a way to do this in Cheshire, this is more of a generic "map transform" feature request, which I think is outside of the scope of Cheshire.
