### ISSUE TITLE
writeNumber turns longs into negative numbers

### ISSUE THREAD

**Issue by kenrestivo** [dakrone/cheshire#36]
I've tried encoding a DateTime into a timestamp, using the following:

``` clojure
(add-encoder  org.joda.time.DateTime
              (fn [c jg]
                (.writeNumber jg  (coerce/to-long c))))
```

Whereas coerce/to-long works fine, .writeNumber does not work: the longs show up as some kind of crazy negative numbers, i.e -189129648.

I tried some experiments.

I tried hardcoding a long in there, to see if .writeNumber might be broken. Indeed, it appears to be broken. In other words:

``` clojure
(add-encoder  org.joda.time.DateTime
              (fn [c jg]
                (.writeNumber jg  1360471091853)))
```

Gives results in the encoded JSON as -1033540979 .

So, maybe writeNumber can't handle longs, even though the javadoc indicates it can? Or is it silently casting to int? I'm unclear. At any rate, this:

``` clojure
(add-encoder  org.joda.time.DateTime
              (fn [c jg]
                (.writeNumber jg  (/ (coerce/to-long c) 1000))))
```

Will generate numbers like 1343962834, which are at least not negative, but have the distinct disadvantage of being completely wrong too.

I may be doing something dumb here, but having a long show up in the generated JSON as a negative int is at least surprising.

Or it may be a bug in jackson-whatever, but I can't chase it quite that far down the rabbit hole at the moment. I haven't been able to find a workaround either.

**Comment by enragedginger** [comment]
3+ years later and this was exactly the solution I was looking for. Thank you!

**Comment by enragedginger** [comment]
2+ years later and this was exactly the solution I was looking for again. Thank you!

**Comment by kenrestivo** [comment]
Bikeshed
```clojure
(add-encoder org.joda.time.Datetime
   (fn [c jg]
     (-> c
          coerce/to-long
          (custom/encode-long jg))))
```
