### ISSUE TITLE
pretty print stream of data

### ISSUE THREAD

**Issue by strattonbrazil** [dakrone/cheshire#74]
Is there a way to pretty-print a stream of data?  I figured generate-string and generate-stream would have comparable options, but only generate-string seems to be pretty printed.  

    (println (generate-string data {:pretty true})) ; pretty-printed
    (generate-stream data (clojure.java.io/writer "test.json")) {:pretty true}) ; not pretty-printed in file

**Comment by dakrone** [comment]
Cheshire already supports this:

```
cheshire.core> (generate-stream {:a "b", :foo "bar"} (java.io.StringWriter.) {:pretty true})
#<StringWriter {
  "foo" : "bar",
  "a" : "b"
}>
cheshire.core> (generate-stream {:a "b", :foo "bar"} (java.io.StringWriter.) {:pretty false})
#<StringWriter {"foo":"bar","a":"b"}>
```

Perhaps clojure's writer is swallowing the newlines?

What version of Cheshire are you using? Can you share example data that reproduces this?

**Comment by dakrone** [comment]
Closed with no feedback, feel free to re-open if needed.
