### ISSUE TITLE
Inconsistent conversion to LazySeq/PersistentVector depending on input

### ISSUE THREAD

**Issue by raspasov** [dakrone/cheshire#76]
(def result (cheshire/parse-string "[1,2,3]"))

(println result) => (1 2 3)
(class result) =>  clojure.lang.LazySeq

(def result-2 (cheshire/parse-string "{\"a\":[1,2,3]}"))
(println result-2) => {"a" [1 2 3]}
(class (get result-2 "a")) => clojure.lang.PersistentVector

Is this inconsistency as designed?

Rangel
@raspasov

PS Nice library, keep up the good work.

**Comment by dakrone** [comment]
Yes, this is by design, cheshire will lazily parse top-level arrays. If you need a different behavior there is `parse-string-strict`, though the lazy parsing has better performance characteristics I believe.

**Comment by raspasov** [comment]
Thanks for the tip! 
Cheers,
Rangel
