### ISSUE TITLE
JSON factory parameters do not work

### ISSUE THREAD

**Issue by noncom** [dakrone/cheshire#78]
I am using Cheshire to create parameters for Neo4j queries out of Clojure maps. The problem is that Neo4j only accepts json (a subset of it, but that's not the case) with unqoted field names. I was unable to make Cheshire behave this way using my custom factory. Probably something is broken. Here are the snippets:

Manually calling and setting the Jackson Java thing (works):

```
(binding [factory/*json-factory* (factory/make-json-factory {})]
   (.disable factory/*json-factory* com.fasterxml.jackson.core.JsonGenerator$Feature/QUOTE_FIELD_NAMES)
   (c/generate-string {:a 1}))
=> "{a:1}"
```

Using Cheshire factory parameters (does not work):

```
(binding [factory/*json-factory* (factory/make-json-factory {:allow-unquoted-field-names true})]
   (c/generate-string {:a 1}))
 => "{\"a\":1}"
```

**Comment by dakrone** [comment]
@noncom okay, I looked at this and the reason why it appears the parameters do not work is that `:allow-unquoted-field-names` is actually a different parameter, for the parser, whereas the `QUOTE_FIELD_NAMES` is a parameter on the generator, which I will need to add support for.

I'll work on adding support for this.
