### ISSUE TITLE
parse-string accepts invalid json string

### ISSUE THREAD

**Issue by Satshabad** [dakrone/cheshire#79]
When I do:

```
 (cheshire.core/parse-string "\"foo\": \"bar\"}")
```

I get

```
"foo"
```

note the lack of a starting `{`

I would expect this to throw an exception instead. May be linked to https://github.com/dakrone/cheshire/issues/65

It must see everything after `"foo"` as junk...

**Comment by cespare** [comment]
This is a duplicate of #65.

**Comment by dakrone** [comment]
closed in #122
