### ISSUE TITLE
Clarity on laziness

### ISSUE THREAD

**Issue by mikera** [dakrone/cheshire#81]
Hello,

I recently had a problem with `parse-stream` in cheshire `5.4.0` acting lazily (it caused a "Stream closed" exception because the lazy loading happened outside the scope of the `with-open` block that created the stream). 

Previously, the same code worked (with an earlier version of cheshire) so I assume that something changed with respect to laziness.

The docstring currently says:

    "If laziness is needed, see parsed-seq"

That sort of implies that `parse-stream` is not meant to be lazy.... but the behaviour implies otherwise. Can we get clarity in the docs on whether this is actually meant to be lazy?

**Comment by dakrone** [comment]
Pushed a commit for this, thanks!
