### ISSUE TITLE
Custom pretty printer

### ISSUE THREAD

**Issue by prayerslayer** [dakrone/cheshire#99]
Currently I see no way of controlling how the pretty printed output is generated. There is the `:pretty` flag, which [uses the default Jackson pretty printer](https://github.com/dakrone/cheshire/blob/016d542cc6fcf4a4760f3498cf84a522e7412c07/src/cheshire/custom.clj#L42). But I want to control e.g. the indentation or whether to create newlines on object start.

Would you be interested in a PR for this? I’m thinking of an API like this

~~~
; {:pretty true} would still do the same, but you can also provide a map with flags

(generate-string {:foo "bar" :baz {:eggplant [1 2 3]}} {:pretty {:indentation 4 :object-key-separator ": "}})
;; {
;;     "foo": "bar",
;;     "baz": {
;;       "eggplant": [ 1, 2, 3 ]
;;     }
;; }
~~~

**Comment by dakrone** [comment]
Sure, I'd be interested in a PR for this, as long as it doesn't affect performance (you can check with `lein core-bench`)
